[package]
name = "zfs-sys"
version = "0.0.0"
authors = ["John Ramsden <johnramsden@riseup.net>"]
edition = "2018"
links = "zfs-sys"

[lib]
name = "zfs_sys"
crate_type = ["dylib"]

[build-dependencies]
pkg-config = "0.3.14"
bindgen = "0.44.0"
